name: Danger

on: [pull_request]

jobs:
  danger:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: yarn install --dev

      - name: Install danger code-coverage and jira-danger
        run: yarn add danger danger-plugin-istanbul-coverage danger-plugin-jira-issue --dev

      - name: Danger
        run: yarn danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
